### ISSUE TITLE
Not able to assign exams to the users migrated from old system.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#70]
Login as institute admin:
code: ins1
email: admin@admin.com
pwd: ins1
go to Manager Users, select one user from the list ....for example .... Deepak Sharma (non-admin), a11@a.com
and and try to assign exams to this user. 
System is throwing error "An internal server error has occurred. Please check the server logs to diagnose the error"

**Comment by ritzforce** [comment]
Done and deployed

**Comment by dipakprogrammer** [comment]
Still Not working....
Login as institute admin:
code: shin
email: admin@admin.com
pwd: shin
go to Manage Users, select one user from the list ....for example .... Deepak Sharma (non-admin), a11@a.com
and and try to assign exams to this user.
System is throwing error "An internal server error has occurred. Please check the server logs to diagnose the error"

**Comment by ritzforce** [comment]
Resolved. The tablename is case sensitive. The actual tablename is "userExam". In database it was "userexam"
